import { defaultSchema } from 'rehype-sanitize'

const styledBlockAttributes = ['className', 'style']
const styledImageAttributes = ['className', 'style', 'src', 'alt', 'title', 'width', 'height']
const svgAttributes = [
  'className',
  'style',
  'xmlns',
  'viewBox',
  'viewbox',
  'width',
  'height',
  'x',
  'y',
  'x1',
  'x2',
  'y1',
  'y2',
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'd',
  'points',
  'fill',
  'stroke',
  'strokeWidth',
  'stroke-width',
  'strokewidth',
  'strokeLinecap',
  'stroke-linecap',
  'strokelinecap',
  'strokeLinejoin',
  'stroke-linejoin',
  'strokelinejoin',
  'strokeDasharray',
  'stroke-dasharray',
  'strokedasharray',
  'strokeDashoffset',
  'stroke-dashoffset',
  'strokedashoffset',
  'opacity',
  'transform',
  'fontSize',
  'font-size',
  'fontsize',
  'fontWeight',
  'font-weight',
  'fontweight',
  'textAnchor',
  'text-anchor',
  'textanchor',
  'dominantBaseline',
  'dominant-baseline',
  'dominantbaseline',
]
const svgAnimationAttributes = [
  'attributeName',
  'attributename',
  'attributeType',
  'attributetype',
  'type',
  'values',
  'from',
  'to',
  'dur',
  'begin',
  'repeatCount',
  'repeatcount',
  'calcMode',
  'calcmode',
  'keyTimes',
  'keytimes',
  'keySplines',
  'keysplines',
  'additive',
]

/**
 * Sanitize schema for rehype-sanitize
 *
 * 注意：Mermaid SVG 仍在 sanitize 之后执行；这里的 SVG 白名单只用于用户主动插入的轻量动态组件。
 */
export const sanitizeSchema = {
  ...defaultSchema,
  protocols: {
    ...(defaultSchema.protocols || {}),
    href: ['http', 'https', 'mailto', 'tel'],
    src: ['http', 'https'],
  },
  tagNames: [
    ...(defaultSchema.tagNames || []),
    'figure',
    'figcaption',
    'section',
    'svg',
    'g',
    'path',
    'circle',
    'rect',
    'line',
    'polyline',
    'polygon',
    'text',
    'tspan',
    'animate',
    'animateTransform',
    'animatetransform',
  ],
  attributes: {
    ...defaultSchema.attributes,
    a: [...(defaultSchema.attributes?.a || []), 'target', 'rel'],
    div: [...(defaultSchema.attributes?.div || []), ...styledBlockAttributes],
    figcaption: [...(defaultSchema.attributes?.figcaption || []), ...styledBlockAttributes],
    figure: [...(defaultSchema.attributes?.figure || []), ...styledBlockAttributes],
    h2: [...(defaultSchema.attributes?.h2 || []), ...styledBlockAttributes],
    h3: [...(defaultSchema.attributes?.h3 || []), ...styledBlockAttributes],
    img: [...(defaultSchema.attributes?.img || []), ...styledImageAttributes],
    svg: svgAttributes,
    g: svgAttributes,
    path: svgAttributes,
    circle: svgAttributes,
    rect: svgAttributes,
    line: svgAttributes,
    polyline: svgAttributes,
    polygon: svgAttributes,
    text: svgAttributes,
    tspan: svgAttributes,
    animate: svgAnimationAttributes,
    animateTransform: svgAnimationAttributes,
    animatetransform: svgAnimationAttributes,
    p: [...(defaultSchema.attributes?.p || []), ...styledBlockAttributes],
    section: [...(defaultSchema.attributes?.section || []), ...styledBlockAttributes],
    span: [...(defaultSchema.attributes?.span || []), ...styledBlockAttributes],
  },
}
