/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as UploadsSplatRouteImport } from './routes/uploads.$'
import { Route as LayoutAboutRouteImport } from './routes/_layout.about'
import { Route as ApiWechatDraftRouteImport } from './routes/api.wechat.draft'
import { Route as ApiWechatComponentRouteImport } from './routes/api.wechat.[component]'
import { Route as ApiWechatCallbackRouteImport } from './routes/api.wechat.callback'
import { Route as ApiWechatAuthorizeRouteImport } from './routes/api.wechat.authorize'
import { Route as ApiWechatAccountRouteImport } from './routes/api.wechat.account'
import { Route as ApiUploadImageRouteImport } from './routes/api.upload.image'
import { Route as ApiImportWechatRouteImport } from './routes/api.import.wechat'
import { Route as LayoutDocsSkillRouteImport } from './routes/_layout.docs.skill'
import { Route as LayoutDocsMcpRouteImport } from './routes/_layout.docs.mcp'
import { Route as ApiWechatDraftSessionRouteImport } from './routes/api.wechat.draft.session'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiWechatDraftRoute = ApiWechatDraftRouteImport.update({
  id: '/api/wechat/draft',
  path: '/api/wechat/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWechatComponentRoute = ApiWechatComponentRouteImport.update({
  id: '/api/wechat/component',
  path: '/api/wechat/component',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWechatCallbackRoute = ApiWechatCallbackRouteImport.update({
  id: '/api/wechat/callback',
  path: '/api/wechat/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWechatAuthorizeRoute = ApiWechatAuthorizeRouteImport.update({
  id: '/api/wechat/authorize',
  path: '/api/wechat/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWechatAccountRoute = ApiWechatAccountRouteImport.update({
  id: '/api/wechat/account',
  path: '/api/wechat/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload/image',
  path: '/api/upload/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportWechatRoute = ApiImportWechatRouteImport.update({
  id: '/api/import/wechat',
  path: '/api/import/wechat',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDocsSkillRoute = LayoutDocsSkillRouteImport.update({
  id: '/docs/skill',
  path: '/docs/skill',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocsMcpRoute = LayoutDocsMcpRouteImport.update({
  id: '/docs/mcp',
  path: '/docs/mcp',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiWechatDraftSessionRoute = ApiWechatDraftSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiWechatDraftRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/mcp': typeof McpRoute
  '/about': typeof LayoutAboutRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/docs/mcp': typeof LayoutDocsMcpRoute
  '/docs/skill': typeof LayoutDocsSkillRoute
  '/api/import/wechat': typeof ApiImportWechatRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/wechat/account': typeof ApiWechatAccountRoute
  '/api/wechat/authorize': typeof ApiWechatAuthorizeRoute
  '/api/wechat/callback': typeof ApiWechatCallbackRoute
  '/api/wechat/component': typeof ApiWechatComponentRoute
  '/api/wechat/draft': typeof ApiWechatDraftRouteWithChildren
  '/api/wechat/draft/session': typeof ApiWechatDraftSessionRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/about': typeof LayoutAboutRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/': typeof LayoutIndexRoute
  '/docs/mcp': typeof LayoutDocsMcpRoute
  '/docs/skill': typeof LayoutDocsSkillRoute
  '/api/import/wechat': typeof ApiImportWechatRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/wechat/account': typeof ApiWechatAccountRoute
  '/api/wechat/authorize': typeof ApiWechatAuthorizeRoute
  '/api/wechat/callback': typeof ApiWechatCallbackRoute
  '/api/wechat/component': typeof ApiWechatComponentRoute
  '/api/wechat/draft': typeof ApiWechatDraftRouteWithChildren
  '/api/wechat/draft/session': typeof ApiWechatDraftSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/mcp': typeof McpRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/docs/mcp': typeof LayoutDocsMcpRoute
  '/_layout/docs/skill': typeof LayoutDocsSkillRoute
  '/api/import/wechat': typeof ApiImportWechatRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/api/wechat/account': typeof ApiWechatAccountRoute
  '/api/wechat/authorize': typeof ApiWechatAuthorizeRoute
  '/api/wechat/callback': typeof ApiWechatCallbackRoute
  '/api/wechat/component': typeof ApiWechatComponentRoute
  '/api/wechat/draft': typeof ApiWechatDraftRouteWithChildren
  '/api/wechat/draft/session': typeof ApiWechatDraftSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/about'
    | '/uploads/$'
    | '/docs/mcp'
    | '/docs/skill'
    | '/api/import/wechat'
    | '/api/upload/image'
    | '/api/wechat/account'
    | '/api/wechat/authorize'
    | '/api/wechat/callback'
    | '/api/wechat/component'
    | '/api/wechat/draft'
    | '/api/wechat/draft/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/about'
    | '/uploads/$'
    | '/'
    | '/docs/mcp'
    | '/docs/skill'
    | '/api/import/wechat'
    | '/api/upload/image'
    | '/api/wechat/account'
    | '/api/wechat/authorize'
    | '/api/wechat/callback'
    | '/api/wechat/component'
    | '/api/wechat/draft'
    | '/api/wechat/draft/session'
  id:
    | '__root__'
    | '/_layout'
    | '/mcp'
    | '/_layout/about'
    | '/uploads/$'
    | '/_layout/'
    | '/_layout/docs/mcp'
    | '/_layout/docs/skill'
    | '/api/import/wechat'
    | '/api/upload/image'
    | '/api/wechat/account'
    | '/api/wechat/authorize'
    | '/api/wechat/callback'
    | '/api/wechat/component'
    | '/api/wechat/draft'
    | '/api/wechat/draft/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  McpRoute: typeof McpRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  ApiImportWechatRoute: typeof ApiImportWechatRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  ApiWechatAccountRoute: typeof ApiWechatAccountRoute
  ApiWechatAuthorizeRoute: typeof ApiWechatAuthorizeRoute
  ApiWechatCallbackRoute: typeof ApiWechatCallbackRoute
  ApiWechatComponentRoute: typeof ApiWechatComponentRoute
  ApiWechatDraftRoute: typeof ApiWechatDraftRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/wechat/draft': {
      id: '/api/wechat/draft'
      path: '/api/wechat/draft'
      fullPath: '/api/wechat/draft'
      preLoaderRoute: typeof ApiWechatDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wechat/component': {
      id: '/api/wechat/component'
      path: '/api/wechat/component'
      fullPath: '/api/wechat/component'
      preLoaderRoute: typeof ApiWechatComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wechat/callback': {
      id: '/api/wechat/callback'
      path: '/api/wechat/callback'
      fullPath: '/api/wechat/callback'
      preLoaderRoute: typeof ApiWechatCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wechat/authorize': {
      id: '/api/wechat/authorize'
      path: '/api/wechat/authorize'
      fullPath: '/api/wechat/authorize'
      preLoaderRoute: typeof ApiWechatAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wechat/account': {
      id: '/api/wechat/account'
      path: '/api/wechat/account'
      fullPath: '/api/wechat/account'
      preLoaderRoute: typeof ApiWechatAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/image': {
      id: '/api/upload/image'
      path: '/api/upload/image'
      fullPath: '/api/upload/image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/wechat': {
      id: '/api/import/wechat'
      path: '/api/import/wechat'
      fullPath: '/api/import/wechat'
      preLoaderRoute: typeof ApiImportWechatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/docs/skill': {
      id: '/_layout/docs/skill'
      path: '/docs/skill'
      fullPath: '/docs/skill'
      preLoaderRoute: typeof LayoutDocsSkillRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docs/mcp': {
      id: '/_layout/docs/mcp'
      path: '/docs/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof LayoutDocsMcpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/wechat/draft/session': {
      id: '/api/wechat/draft/session'
      path: '/session'
      fullPath: '/api/wechat/draft/session'
      preLoaderRoute: typeof ApiWechatDraftSessionRouteImport
      parentRoute: typeof ApiWechatDraftRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDocsMcpRoute: typeof LayoutDocsMcpRoute
  LayoutDocsSkillRoute: typeof LayoutDocsSkillRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDocsMcpRoute: LayoutDocsMcpRoute,
  LayoutDocsSkillRoute: LayoutDocsSkillRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ApiWechatDraftRouteChildren {
  ApiWechatDraftSessionRoute: typeof ApiWechatDraftSessionRoute
}

const ApiWechatDraftRouteChildren: ApiWechatDraftRouteChildren = {
  ApiWechatDraftSessionRoute: ApiWechatDraftSessionRoute,
}

const ApiWechatDraftRouteWithChildren = ApiWechatDraftRoute._addFileChildren(
  ApiWechatDraftRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  McpRoute: McpRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  ApiImportWechatRoute: ApiImportWechatRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
  ApiWechatAccountRoute: ApiWechatAccountRoute,
  ApiWechatAuthorizeRoute: ApiWechatAuthorizeRoute,
  ApiWechatCallbackRoute: ApiWechatCallbackRoute,
  ApiWechatComponentRoute: ApiWechatComponentRoute,
  ApiWechatDraftRoute: ApiWechatDraftRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
